services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: points_bd_service
    environment:
      - POSTGRES_DB=points_bd
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123456
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todo_network

  api:
    build:
      context: ./smart_api
      dockerfile: Dockerfile
    container_name: smart_api
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin123456
      - DB_NAME=points_bd
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./smart_api/src:/app/src
    networks:
      - todo_network

volumes:
  postgres_data:
    driver: local

networks:
  todo_network:
    driver: bridge
