services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: points_bd_service
    environment:
      - POSTGRES_DB=points_bd
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123456
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=localhost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todo_network

volumes:
  postgres_data:
    driver: local

networks:
  todo_network:
    driver: bridge
